#!/bin/sh

# generate: generates html and index pages from markdown posts.
#           functions are meant to be executed by make through the makefile
#           which handles dependencies between files. no configuration should go
#           here, everything (i.e. filenames) is passed by make.

set -e

#
# utils
#

dieifempty() {
        if [ -z "$1" ]; then
                echo "error: $2" >&2
                exit 1
        fi
}

#
# actions
#

indexhtml() {
        headerhtml="$1"
        indexmd="$2"

        cat "$headerhtml"
        sed -n -e '1 s/^/<title>/' -e '1 s/$/<\/title>/p' "$indexmd"
        cmark "$indexmd" | sed -e 's/\.md/\.html/g' | tac | awk '!f && /<ul>/ { $0="<ul class=\"no-bullet\">"; f=1 } 1' | tac
}

indexmd() {
        aboutmd="$1"
        shift # rest of arguments are markdown posts filenames

        cat "$aboutmd"
        printf "\nposts\n-----\n\n"
        tmp="$(mktemp)"
        for post in "$@"; do
                date="$(sed -n '1p' "$post")"
                title="$(sed -n '3p' "$post")"
                printf "%c %s [%s](%s)\n" "-" "$date" "$title" "$post" >> "$tmp"
        done
        sort -r "$tmp"
        rm "$tmp"
}

posthtml() {
        headerhtml="$1"
        postmd="$2"
        footerhtml="$3"

        sed 's/href="/href="..\//g' "$headerhtml"
        sed -n -e '3 s/^/<title>/' -e '3 s/$/<\/title>/p' "$postmd"
        cmark "$postmd"
        sed 's/href="/href="..\//g' "$footerhtml"
}

newpost() {
        postsdir="$1"
        title="$2"
        dieifempty "$title" "missing TITLE=\"\""

        post="$postsdir/$(echo "$title" | sed -e 's/\s\+/-/g' -e 's/$/.md/')"
        date="$(date +"%Y-%m-%d")"
        titlelen="$(printf "%s" "$title" | wc -m)"
        heading="$(yes '=' | head -n "$titlelen" | tr -d '\n')"
        printf "%s\n\n%s\n%s\n\n\n" "$date" "$title" "$heading" >> "$post"
        vi "$post"
}

#
# main
#

action="$1"
dieifempty "$action" "missing action"
shift
$action "$@"
